# Generated by Django 3.2.18 on 2023-05-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_ids',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
