# Generated by Django 3.2.18 on 2023-05-21 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='register_manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='register_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
