# Generated by Django 3.2.18 on 2023-05-20 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_movie_like_movie_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='register_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='register_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
