# Generated by Django 3.2.18 on 2023-05-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_follow_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='follow_users',
        ),
    ]
