# Generated by Django 3.2.18 on 2023-05-21 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_remove_movie_follow_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like_movie_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='register_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
