# Generated by Django 3.2.18 on 2023-05-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230521_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='like_movie_users',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='register_manager',
        ),
    ]
